# Generated by Django 2.2.4 on 2019-08-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('title', models.TextField(max_length=150)),
                ('content', models.TextField()),
                ('dateCreated', models.DateField()),
            ],
        ),
    ]
