# Generated by Django 2.2.4 on 2019-08-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.TextField(max_length=150)),
                ('summary', models.TextField(max_length=300)),
                ('started', models.DateField()),
                ('ended', models.DateField()),
                ('assignedTo', models.TextField(max_length=150)),
            ],
        ),
    ]
